### ISSUE TITLE
How to compile with BTF and not DWARF

### ISSUE THREAD

**Issue by vincentroberge** [pathtofile/volatility2-profile-ubuntu2104#1]
Hi. I am trying to build a Volatility 2 profile for Ubuntu 22.04. I am able to follow the procedure on the Volatility Foundation page ([https://github.com/volatilityfoundation/volatility/wiki/Linux]) and I can successfully build the profile, but it generates errors when I try to use the profile in Volatility 2. I suspect that the kernel or Dwarfdump is too recent for Volatility 2.6.1. I found very little help online, except your github page which shows that you have successfully done it for Ubuntu 21.04. This is close to 22.04. How did you do it exactly? You point to the Volatility Foundation How-to, but you say that you have used BTF instead of DWARF. On their How-to, they use DWARF. Any help would be appreciated.

This is the error that I get, when I try to use my Ubuntu 22.04 profile on Volatility 2.6.1.
```
$ vol.py -f ubuntu.vmem --profile=Linuxubuntu-22.04-desktop-amd64_5.15.0-33-genericx64 linux_pslist
Volatility Foundation Volatility Framework 2.6.1
Traceback (most recent call last):
  File "/usr/local/bin/vol.py", line 192, in <module>
    main()
  File "/usr/local/bin/vol.py", line 183, in main
    command.execute()
  File "/usr/local/lib/python2.7/dist-packages/volatility/plugins/linux/common.py", line 67, in execute
    commands.Command.execute(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/volatility/commands.py", line 116, in execute
    if not self.is_valid_profile(profs[self._config.PROFILE]()):
  File "/usr/local/lib/python2.7/dist-packages/volatility/plugins/overlays/linux/linux.py", line 218, in __init__
    obj.Profile.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/volatility/obj.py", line 862, in __init__
    self.reset()
  File "/usr/local/lib/python2.7/dist-packages/volatility/plugins/overlays/linux/linux.py", line 232, in reset
    self.load_vtypes()
  File "/usr/local/lib/python2.7/dist-packages/volatility/plugins/overlays/linux/linux.py", line 269, in load_vtypes
    vtypesvar = dwarf.DWARFParser(dwarfdata).finalize()
  File "/usr/local/lib/python2.7/dist-packages/volatility/dwarf.py", line 72, in __init__
    self.feed_line(line)
  File "/usr/local/lib/python2.7/dist-packages/volatility/dwarf.py", line 161, in feed_line
    self.process_variable(parsed['data'])
  File "/usr/local/lib/python2.7/dist-packages/volatility/dwarf.py", line 330, in process_variable
    data['DW_AT_decl_file'].split()[1], data['DW_AT_type']))
IndexError: list index out of range
```

Vincent

**Comment by pathtofile** [comment]
Sorry @vincentroberge - Now with Volatility 2 being deprecated, and it being such a long time since I used this project, I'm closing this issue and archiving the project
